-- ============================================================
-- CREATE PARKING SLOTS TABLE AND CONFIG RLS POLICIES
-- ============================================================

CREATE TABLE IF NOT EXISTS public.parking_slots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    free_spaces INT NOT NULL,
    snapshot_path TEXT NOT NULL
);

-- Enable Row Level Security (RLS) on the data layer
ALTER TABLE public.parking_slots ENABLE ROW LEVEL SECURITY;

-- Create declarative policies to allow administrative actions and read bounds
CREATE POLICY "Allow service_role full access"
ON public.parking_slots
FOR ALL
TO service_role
USING (true)
WITH CHECK (true);

CREATE POLICY "Allow authenticated inserts"
ON public.parking_slots
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Allow public read visibility"
ON public.parking_slots
FOR SELECT
TO public
USING (true);
