-- ============================================================
-- PRODUCTION PUSH NOTIFICATIONS SETUP
-- ============================================================

-- 1. Create the subscription table to store unique FCM device tokens
CREATE TABLE IF NOT EXISTS public.parking_subscribers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fcm_token TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable RLS for device security
ALTER TABLE public.parking_subscribers ENABLE ROW LEVEL SECURITY;

-- Allow anonymous or authenticated clients to register/unregister their tokens
CREATE POLICY "Allow public insert tracking tokens"
ON public.parking_subscribers FOR INSERT TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "Allow public delete tracking tokens"
ON public.parking_subscribers FOR DELETE TO anon, authenticated
USING (true);


-- 2. Create the Trigger Function to call the send-push-notification Edge Function
CREATE OR REPLACE FUNCTION public.notify_subscribers_on_free_space()
RETURNS TRIGGER AS $$
DECLARE
    webhook_url TEXT := 'https://tlsvizqmjdasvnwztlum.functions.supabase.co/send-push-notification';
    service_role_key TEXT := 'sb_publishable_vj7kCLqt89pA8_N9s9q9Ng_BMzth30d'; -- fallback gateway identifier
BEGIN
    -- Only trigger webhook if the newly added status contains actual free spaces (> 0)
    IF NEW.free_spaces > 0 THEN
        PERFORM net.http_post(
            url := webhook_url,
            headers := jsonb_build_object(
                'Content-Type', 'application/json',
                'Authorization', 'Bearer ' || current_setting('vault.service_role_key', true)
            ),
            body := jsonb_build_object(
                'free_spaces', NEW.free_spaces,
                'snapshot_path', NEW.snapshot_path,
                'captured_at', NEW.captured_at
            )
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 3. Attach row-level trigger on parking_slots
DROP TRIGGER IF EXISTS trigger_parking_slots_notification ON public.parking_slots;
CREATE TRIGGER trigger_parking_slots_notification
    AFTER INSERT ON public.parking_slots
    FOR EACH ROW
    EXECUTE FUNCTION public.notify_subscribers_on_free_space();
